FROM python:3.12

WORKDIR /flask

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY frontend/* ./

RUN pip install -r requirements.txt

CMD ["gunicorn", "--bind=0.0.0.0:5000", "--workers=4", "start:app"]